[command]
name = "defender-force"
keywords = ["performance", "security"]
enabled = true
content = """
If you're having problems with re-enabling the Windows Defender, try this.

Open up a new Terminal/Powershell window (as admin) and enter these commands:

`& "$env:PROGRAMFILES\\Revision Tool\\revitool.exe" defender disable --force`

restart, then

`& "$env:PROGRAMFILES\\Revision Tool\\revitool.exe" defender enable --force`
"""

[embed]
enabled = true
