[command]
name = "donate"
keywords = ["support", "project"]
enabled = true
content = """
If you want to support the Revision Project and the people behind it, you can leave us a donation here: https://revi.cc/donate/ ğŸ¤
"""

[embed]
enabled = true
