[command]
name = "logs"
keywords = ["revision tool", "ame", "splines"]
enabled = true
content = """
Ran into an error and need to find the logs?

If the error happened during installation, open Run (Win + R) and check here:
```
%programdata%\\AME\\Logs
```

If the error is related to the Revision Tool, open Run (Win + R) check here:
```
%temp%\\Revision-Tool\\Logs
```

If staff asks for logs, please provide the contents of these folders to help with troubleshooting.
"""

[embed]
enabled = true
