[command]
name = "update-fix"
keywords = ["windows"]
enabled = true
content = """
In case you are having issues with installing a Windows update, use the following commands to attempt to fix the issue:

- `DISM /Online /Cleanup-Image /RestoreHealth`
- `SFC /scannow` 
"""

[embed]
enabled = true
