[command]
name = "wallpaper"
keywords = ["background", "desktop", "lockscreen"]
enabled = true
content = """
# ReviOS Wallpapers

## Desktop
ğŸ–¥ï¸<https://raw.githubusercontent.com/meetrevision/playbook/main/src/Executables/Wallpapers/desktop.jpg>

## Lock Screen
ğŸ”’<https://raw.githubusercontent.com/meetrevision/playbook/main/src/Executables/Wallpapers/lockscreen.jpg>
"""

[embed]
enabled = false
